name: LOCStats
version: 0.0.6
description: LOCStats is a local player-stat system
author: Th3Shadowbroker
website: http://crafter629.de
main: com.th3shadowbroker.loc.main
load: STARTUP

commands:
     loc:
        description: All you need to know.
        permission: locstats.admin